#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDuAn
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THUHOCPHI")]
	public partial class DbThuHocPhiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdkbldqt(dkbldqt instance);
    partial void Updatedkbldqt(dkbldqt instance);
    partial void Deletedkbldqt(dkbldqt instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertHocKy(HocKy instance);
    partial void UpdateHocKy(HocKy instance);
    partial void DeleteHocKy(HocKy instance);
    partial void Insertkqdk_dqt(kqdk_dqt instance);
    partial void Updatekqdk_dqt(kqdk_dqt instance);
    partial void Deletekqdk_dqt(kqdk_dqt instance);
    partial void InsertMonHoc(MonHoc instance);
    partial void UpdateMonHoc(MonHoc instance);
    partial void DeleteMonHoc(MonHoc instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public DbThuHocPhiDataContext() : 
				base(global::QuanLiDuAn.Properties.Settings.Default.THUHOCPHIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbThuHocPhiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbThuHocPhiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbThuHocPhiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbThuHocPhiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dkbldqt> dkbldqts
		{
			get
			{
				return this.GetTable<dkbldqt>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<gdt_payer_escape> gdt_payer_escapes
		{
			get
			{
				return this.GetTable<gdt_payer_escape>();
			}
		}
		
		public System.Data.Linq.Table<HocKy> HocKies
		{
			get
			{
				return this.GetTable<HocKy>();
			}
		}
		
		public System.Data.Linq.Table<kqdk_dqt> kqdk_dqts
		{
			get
			{
				return this.GetTable<kqdk_dqt>();
			}
		}
		
		public System.Data.Linq.Table<kqthuhocphi17_2> kqthuhocphi17_2s
		{
			get
			{
				return this.GetTable<kqthuhocphi17_2>();
			}
		}
		
		public System.Data.Linq.Table<KQTHUHOCPHI19_2> KQTHUHOCPHI19_2s
		{
			get
			{
				return this.GetTable<KQTHUHOCPHI19_2>();
			}
		}
		
		public System.Data.Linq.Table<kqthuhocphi22_2> kqthuhocphi22_2s
		{
			get
			{
				return this.GetTable<kqthuhocphi22_2>();
			}
		}
		
		public System.Data.Linq.Table<MonHoc> MonHocs
		{
			get
			{
				return this.GetTable<MonHoc>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dkbldqt")]
	public partial class dkbldqt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _MaLop;
		
		private System.Nullable<System.DateTime> _NgayDong;
		
		private System.Nullable<decimal> _SoTien;
		
		private System.Nullable<int> _TongSoTC;
		
		private string _NguoiThu;
		
		private int _HocKyID;
		
		private string _Log;
		
		private int _SoPhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenSVChanging(string value);
    partial void OnHoTenSVChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnNgayDongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDongChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnTongSoTCChanging(System.Nullable<int> value);
    partial void OnTongSoTCChanged();
    partial void OnNguoiThuChanging(string value);
    partial void OnNguoiThuChanged();
    partial void OnHocKyIDChanging(int value);
    partial void OnHocKyIDChanged();
    partial void OnLogChanging(string value);
    partial void OnLogChanged();
    partial void OnSoPhieuChanging(int value);
    partial void OnSoPhieuChanged();
    #endregion
		
		public dkbldqt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(200)")]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this.OnHoTenSVChanging(value);
					this.SendPropertyChanging();
					this._HoTenSV = value;
					this.SendPropertyChanged("HoTenSV");
					this.OnHoTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="VarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDong
		{
			get
			{
				return this._NgayDong;
			}
			set
			{
				if ((this._NgayDong != value))
				{
					this.OnNgayDongChanging(value);
					this.SendPropertyChanging();
					this._NgayDong = value;
					this.SendPropertyChanged("NgayDong");
					this.OnNgayDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Money")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTC", DbType="Int")]
		public System.Nullable<int> TongSoTC
		{
			get
			{
				return this._TongSoTC;
			}
			set
			{
				if ((this._TongSoTC != value))
				{
					this.OnTongSoTCChanging(value);
					this.SendPropertyChanging();
					this._TongSoTC = value;
					this.SendPropertyChanged("TongSoTC");
					this.OnTongSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThu", DbType="NVarChar(200)")]
		public string NguoiThu
		{
			get
			{
				return this._NguoiThu;
			}
			set
			{
				if ((this._NguoiThu != value))
				{
					this.OnNguoiThuChanging(value);
					this.SendPropertyChanging();
					this._NguoiThu = value;
					this.SendPropertyChanged("NguoiThu");
					this.OnNguoiThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", DbType="Int NOT NULL")]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this.OnHocKyIDChanging(value);
					this.SendPropertyChanging();
					this._HocKyID = value;
					this.SendPropertyChanged("HocKyID");
					this.OnHocKyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Log]", Storage="_Log", DbType="NVarChar(255)")]
		public string Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				if ((this._Log != value))
				{
					this.OnLogChanging(value);
					this.SendPropertyChanging();
					this._Log = value;
					this.SendPropertyChanged("Log");
					this.OnLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private string _HoTen;
		
		private System.Nullable<int> _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnPhoneChanging(System.Nullable<int> value);
    partial void OnPhoneChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Int")]
		public System.Nullable<int> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gdt_payer_escape")]
	public partial class gdt_payer_escape
	{
		
		private string _taxoffice_name;
		
		private string _payer_code;
		
		private string _payer_name;
		
		private string _owner_id_card;
		
		private System.Nullable<System.DateTime> _escape_date;
		
		private string _warning_info;
		
		private string _storage_symbol;
		
		private string _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _deleted_by;
		
		private System.Nullable<System.DateTime> _deleted_date;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_date;
		
		private string _file_upload;
		
		public gdt_payer_escape()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxoffice_name", DbType="NVarChar(2000)")]
		public string taxoffice_name
		{
			get
			{
				return this._taxoffice_name;
			}
			set
			{
				if ((this._taxoffice_name != value))
				{
					this._taxoffice_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payer_code", DbType="NVarChar(20)")]
		public string payer_code
		{
			get
			{
				return this._payer_code;
			}
			set
			{
				if ((this._payer_code != value))
				{
					this._payer_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payer_name", DbType="NVarChar(2000)")]
		public string payer_name
		{
			get
			{
				return this._payer_name;
			}
			set
			{
				if ((this._payer_name != value))
				{
					this._payer_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id_card", DbType="VarChar(500)")]
		public string owner_id_card
		{
			get
			{
				return this._owner_id_card;
			}
			set
			{
				if ((this._owner_id_card != value))
				{
					this._owner_id_card = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_escape_date", DbType="Date")]
		public System.Nullable<System.DateTime> escape_date
		{
			get
			{
				return this._escape_date;
			}
			set
			{
				if ((this._escape_date != value))
				{
					this._escape_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warning_info", DbType="NVarChar(2000)")]
		public string warning_info
		{
			get
			{
				return this._warning_info;
			}
			set
			{
				if ((this._warning_info != value))
				{
					this._warning_info = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storage_symbol", DbType="NVarChar(20)")]
		public string storage_symbol
		{
			get
			{
				return this._storage_symbol;
			}
			set
			{
				if ((this._storage_symbol != value))
				{
					this._storage_symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="VarChar(32)")]
		public string is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this._is_deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(500)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this._created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_by", DbType="VarChar(500)")]
		public string deleted_by
		{
			get
			{
				return this._deleted_by;
			}
			set
			{
				if ((this._deleted_by != value))
				{
					this._deleted_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_date", DbType="Date")]
		public System.Nullable<System.DateTime> deleted_date
		{
			get
			{
				return this._deleted_date;
			}
			set
			{
				if ((this._deleted_date != value))
				{
					this._deleted_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="VarChar(500)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this._modified_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="Date")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this._modified_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_upload", DbType="VarChar(500)")]
		public string file_upload
		{
			get
			{
				return this._file_upload;
			}
			set
			{
				if ((this._file_upload != value))
				{
					this._file_upload = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocKy")]
	public partial class HocKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HocKyID;
		
		private string _HocKy1;
		
		private System.Nullable<decimal> _HocPhi;
		
		private System.Nullable<bool> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHocKyIDChanging(int value);
    partial void OnHocKyIDChanged();
    partial void OnHocKy1Changing(string value);
    partial void OnHocKy1Changed();
    partial void OnHocPhiChanging(System.Nullable<decimal> value);
    partial void OnHocPhiChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public HocKy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this.OnHocKyIDChanging(value);
					this.SendPropertyChanging();
					this._HocKyID = value;
					this.SendPropertyChanged("HocKyID");
					this.OnHocKyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HocKy", Storage="_HocKy1", DbType="VarChar(50)")]
		public string HocKy1
		{
			get
			{
				return this._HocKy1;
			}
			set
			{
				if ((this._HocKy1 != value))
				{
					this.OnHocKy1Changing(value);
					this.SendPropertyChanging();
					this._HocKy1 = value;
					this.SendPropertyChanged("HocKy1");
					this.OnHocKy1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocPhi", DbType="Money")]
		public System.Nullable<decimal> HocPhi
		{
			get
			{
				return this._HocPhi;
			}
			set
			{
				if ((this._HocPhi != value))
				{
					this.OnHocPhiChanging(value);
					this.SendPropertyChanging();
					this._HocPhi = value;
					this.SendPropertyChanged("HocPhi");
					this.OnHocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kqdk_dqt")]
	public partial class kqdk_dqt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTen;
		
		private string _Lop;
		
		private string _MaMH;
		
		private string _TenMH;
		
		private string _Nhhk;
		
		private string _SoTC;
		
		private string _SoTCHP;
		
		private string _Diemqt;
		
		private string _Diemthi;
		
		private string _DiemTk;
		
		private string _Diemso;
		
		private string _Diemchu;
		
		private System.Nullable<System.DateTime> _NgayLuu;
		
		private int _HocKyId;
		
		private string _Log;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnNhhkChanging(string value);
    partial void OnNhhkChanged();
    partial void OnSoTCChanging(string value);
    partial void OnSoTCChanged();
    partial void OnSoTCHPChanging(string value);
    partial void OnSoTCHPChanged();
    partial void OnDiemqtChanging(string value);
    partial void OnDiemqtChanged();
    partial void OnDiemthiChanging(string value);
    partial void OnDiemthiChanged();
    partial void OnDiemTkChanging(string value);
    partial void OnDiemTkChanged();
    partial void OnDiemsoChanging(string value);
    partial void OnDiemsoChanged();
    partial void OnDiemchuChanging(string value);
    partial void OnDiemchuChanged();
    partial void OnNgayLuuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLuuChanged();
    partial void OnHocKyIdChanging(int value);
    partial void OnHocKyIdChanged();
    partial void OnLogChanging(string value);
    partial void OnLogChanged();
    #endregion
		
		public kqdk_dqt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10)")]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(100)")]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhhk", DbType="NVarChar(100)")]
		public string Nhhk
		{
			get
			{
				return this._Nhhk;
			}
			set
			{
				if ((this._Nhhk != value))
				{
					this.OnNhhkChanging(value);
					this.SendPropertyChanging();
					this._Nhhk = value;
					this.SendPropertyChanged("Nhhk");
					this.OnNhhkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTC", DbType="VarChar(5)")]
		public string SoTC
		{
			get
			{
				return this._SoTC;
			}
			set
			{
				if ((this._SoTC != value))
				{
					this.OnSoTCChanging(value);
					this.SendPropertyChanging();
					this._SoTC = value;
					this.SendPropertyChanged("SoTC");
					this.OnSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTCHP", DbType="VarChar(5)")]
		public string SoTCHP
		{
			get
			{
				return this._SoTCHP;
			}
			set
			{
				if ((this._SoTCHP != value))
				{
					this.OnSoTCHPChanging(value);
					this.SendPropertyChanging();
					this._SoTCHP = value;
					this.SendPropertyChanged("SoTCHP");
					this.OnSoTCHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diemqt", DbType="VarChar(5)")]
		public string Diemqt
		{
			get
			{
				return this._Diemqt;
			}
			set
			{
				if ((this._Diemqt != value))
				{
					this.OnDiemqtChanging(value);
					this.SendPropertyChanging();
					this._Diemqt = value;
					this.SendPropertyChanged("Diemqt");
					this.OnDiemqtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diemthi", DbType="VarChar(5)")]
		public string Diemthi
		{
			get
			{
				return this._Diemthi;
			}
			set
			{
				if ((this._Diemthi != value))
				{
					this.OnDiemthiChanging(value);
					this.SendPropertyChanging();
					this._Diemthi = value;
					this.SendPropertyChanged("Diemthi");
					this.OnDiemthiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemTk", DbType="VarChar(6)")]
		public string DiemTk
		{
			get
			{
				return this._DiemTk;
			}
			set
			{
				if ((this._DiemTk != value))
				{
					this.OnDiemTkChanging(value);
					this.SendPropertyChanging();
					this._DiemTk = value;
					this.SendPropertyChanged("DiemTk");
					this.OnDiemTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diemso", DbType="VarChar(6)")]
		public string Diemso
		{
			get
			{
				return this._Diemso;
			}
			set
			{
				if ((this._Diemso != value))
				{
					this.OnDiemsoChanging(value);
					this.SendPropertyChanging();
					this._Diemso = value;
					this.SendPropertyChanged("Diemso");
					this.OnDiemsoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diemchu", DbType="VarChar(6)")]
		public string Diemchu
		{
			get
			{
				return this._Diemchu;
			}
			set
			{
				if ((this._Diemchu != value))
				{
					this.OnDiemchuChanging(value);
					this.SendPropertyChanging();
					this._Diemchu = value;
					this.SendPropertyChanged("Diemchu");
					this.OnDiemchuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLuu", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLuu
		{
			get
			{
				return this._NgayLuu;
			}
			set
			{
				if ((this._NgayLuu != value))
				{
					this.OnNgayLuuChanging(value);
					this.SendPropertyChanging();
					this._NgayLuu = value;
					this.SendPropertyChanged("NgayLuu");
					this.OnNgayLuuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HocKyId
		{
			get
			{
				return this._HocKyId;
			}
			set
			{
				if ((this._HocKyId != value))
				{
					this.OnHocKyIdChanging(value);
					this.SendPropertyChanging();
					this._HocKyId = value;
					this.SendPropertyChanged("HocKyId");
					this.OnHocKyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Log]", Storage="_Log", DbType="NVarChar(255)")]
		public string Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				if ((this._Log != value))
				{
					this.OnLogChanging(value);
					this.SendPropertyChanging();
					this._Log = value;
					this.SendPropertyChanged("Log");
					this.OnLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kqthuhocphi17_2")]
	public partial class kqthuhocphi17_2
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _MaLop;
		
		private System.Nullable<int> _TongSoTC;
		
		private System.Nullable<System.DateTime> _NgayDong;
		
		private string _NguoiThu;
		
		private int _HocKyID;
		
		private string _Log;
		
		private System.Nullable<int> _SoPhieu;
		
		public kqthuhocphi17_2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(200)")]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="VarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTC", DbType="Int")]
		public System.Nullable<int> TongSoTC
		{
			get
			{
				return this._TongSoTC;
			}
			set
			{
				if ((this._TongSoTC != value))
				{
					this._TongSoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDong
		{
			get
			{
				return this._NgayDong;
			}
			set
			{
				if ((this._NgayDong != value))
				{
					this._NgayDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThu", DbType="NVarChar(200)")]
		public string NguoiThu
		{
			get
			{
				return this._NguoiThu;
			}
			set
			{
				if ((this._NguoiThu != value))
				{
					this._NguoiThu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", DbType="Int NOT NULL")]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this._HocKyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Log]", Storage="_Log", DbType="NVarChar(255)")]
		public string Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				if ((this._Log != value))
				{
					this._Log = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Int")]
		public System.Nullable<int> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KQTHUHOCPHI19_2")]
	public partial class KQTHUHOCPHI19_2
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _MaLop;
		
		private System.Nullable<int> _TongSoTC;
		
		private System.Nullable<System.DateTime> _NgayDong;
		
		private string _NguoiThu;
		
		private int _HocKyID;
		
		private string _Log;
		
		private System.Nullable<int> _SoPhieu;
		
		public KQTHUHOCPHI19_2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(200)")]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="VarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTC", DbType="Int")]
		public System.Nullable<int> TongSoTC
		{
			get
			{
				return this._TongSoTC;
			}
			set
			{
				if ((this._TongSoTC != value))
				{
					this._TongSoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDong
		{
			get
			{
				return this._NgayDong;
			}
			set
			{
				if ((this._NgayDong != value))
				{
					this._NgayDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThu", DbType="NVarChar(200)")]
		public string NguoiThu
		{
			get
			{
				return this._NguoiThu;
			}
			set
			{
				if ((this._NguoiThu != value))
				{
					this._NguoiThu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", DbType="Int NOT NULL")]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this._HocKyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Log]", Storage="_Log", DbType="NVarChar(255)")]
		public string Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				if ((this._Log != value))
				{
					this._Log = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Int")]
		public System.Nullable<int> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kqthuhocphi22_2")]
	public partial class kqthuhocphi22_2
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _MaLop;
		
		private System.Nullable<int> _TongSoTC;
		
		private System.Nullable<System.DateTime> _NgayDong;
		
		private string _NguoiThu;
		
		private int _HocKyID;
		
		private string _Log;
		
		private System.Nullable<int> _SoPhieu;
		
		public kqthuhocphi22_2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(200)")]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="VarChar(50)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this._MaLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTC", DbType="Int")]
		public System.Nullable<int> TongSoTC
		{
			get
			{
				return this._TongSoTC;
			}
			set
			{
				if ((this._TongSoTC != value))
				{
					this._TongSoTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDong
		{
			get
			{
				return this._NgayDong;
			}
			set
			{
				if ((this._NgayDong != value))
				{
					this._NgayDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThu", DbType="NVarChar(200)")]
		public string NguoiThu
		{
			get
			{
				return this._NguoiThu;
			}
			set
			{
				if ((this._NguoiThu != value))
				{
					this._NguoiThu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKyID", DbType="Int NOT NULL")]
		public int HocKyID
		{
			get
			{
				return this._HocKyID;
			}
			set
			{
				if ((this._HocKyID != value))
				{
					this._HocKyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Log]", Storage="_Log", DbType="NVarChar(255)")]
		public string Log
		{
			get
			{
				return this._Log;
			}
			set
			{
				if ((this._Log != value))
				{
					this._Log = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Int")]
		public System.Nullable<int> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonHoc")]
	public partial class MonHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMH;
		
		private string _TenMH;
		
		private string _SoTCHP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMHChanging(string value);
    partial void OnMaMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnSoTCHPChanging(string value);
    partial void OnSoTCHPChanged();
    #endregion
		
		public MonHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(100)")]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTCHP", DbType="VarChar(5)")]
		public string SoTCHP
		{
			get
			{
				return this._SoTCHP;
			}
			set
			{
				if ((this._SoTCHP != value))
				{
					this.OnSoTCHPChanging(value);
					this.SendPropertyChanging();
					this._SoTCHP = value;
					this.SendPropertyChanged("SoTCHP");
					this.OnSoTCHPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSv;
		
		private string _HoTen;
		
		private string _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSvChanging(string value);
    partial void OnMaSvChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    #endregion
		
		public SinhVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSv", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSv
		{
			get
			{
				return this._MaSv;
			}
			set
			{
				if ((this._MaSv != value))
				{
					this.OnMaSvChanging(value);
					this.SendPropertyChanging();
					this._MaSv = value;
					this.SendPropertyChanged("MaSv");
					this.OnMaSvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10)")]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
